### ISSUE TITLE
Fix font style for code blocks

### ISSUE THREAD

**Issue by krokofant** [Chrismettal/Obsidian-Behave-dark#1]
![image](https://user-images.githubusercontent.com/5908498/134415324-89860b9e-02fd-414f-b956-6b3732bfc7cc.png)

Could this be set to some sans-serif font? Maybe the same font used for the editor?
```
var(--font-family-editor)
```

**Comment by Chrismettal** [comment]
Thanks for the suggestion, you are right, I totally missed that one. I just pushed your suggested fix to the repo so you might need to re-download the theme. Don't think they update on their own.
